package com.H_SerhatY.MoreStrenghtenedToolsMod.init;

import java.util.ArrayList;
import java.util.List;

import com.H_SerhatY.MoreStrenghtenedToolsMod.items.ItemBase;
import com.H_SerhatY.MoreStrenghtenedToolsMod.items.armor.ArmorBase;
import com.H_SerhatY.MoreStrenghtenedToolsMod.items.tools.ToolAxe;
import com.H_SerhatY.MoreStrenghtenedToolsMod.items.tools.ToolHoe;
import com.H_SerhatY.MoreStrenghtenedToolsMod.items.tools.ToolPickaxe;
import com.H_SerhatY.MoreStrenghtenedToolsMod.items.tools.ToolSpade;
import com.H_SerhatY.MoreStrenghtenedToolsMod.items.tools.ToolSword;
import com.H_SerhatY.MoreStrenghtenedToolsMod.util.Reference;

import net.minecraft.init.SoundEvents;
import net.minecraft.inventory.EntityEquipmentSlot;
import net.minecraft.item.Item;
import net.minecraft.item.Item.ToolMaterial;
import net.minecraft.item.ItemArmor.ArmorMaterial;
import net.minecraft.item.ItemAxe;
import net.minecraft.item.ItemHoe;
import net.minecraft.item.ItemPickaxe;
import net.minecraft.item.ItemSpade;
import net.minecraft.item.ItemSword;
import net.minecraftforge.common.util.EnumHelper;

public class ModItems 
{
	
	public static final List<Item> ITEMS = new ArrayList<Item>();
	
	//Materials
	public static final ToolMaterial MATERIAL_REINFORCED_WOODEN_PLANKS_MK1 = EnumHelper.addToolMaterial("material_reinforced_wooden_planks_mk1", 0, 77, 3.0F, 1.0F, 20);
	public static final ToolMaterial MATERIAL_REINFORCED_WOODEN_PLANKS_MK2 = EnumHelper.addToolMaterial("material_reinforced_wooden_planks_mk2", 0, 100, 4.0F, 3.0F, 26);
	public static final ToolMaterial MATERIAL_REINFORCED_WOODEN_PLANKS_MK3 = EnumHelper.addToolMaterial("material_reinforced_wooden_planks_mk3", 0, 130, 5.0F, 5.0F, 34);
	public static final ToolMaterial MATERIAL_REINFORCED_WOODEN_PLANKS_MK4 = EnumHelper.addToolMaterial("material_reinforced_wooden_planks_mk4", 0, 169, 7.0F, 8.0F, 44);
	public static final ToolMaterial MATERIAL_REINFORCED_COBBLESTONE_MK1 = EnumHelper.addToolMaterial("material_reinforced_cobblestone_mk1", 2, 197, 6.0F, 4.0F, 8);
	public static final ToolMaterial MATERIAL_REINFORCED_COBBLESTONE_MK2 = EnumHelper.addToolMaterial("material_reinforced_cobblestone_mk2", 3, 296, 9.0F, 8.0F, 12);
	public static final ToolMaterial MATERIAL_REINFORCED_COBBLESTONE_MK3 = EnumHelper.addToolMaterial("material_reinforced_cobblestone_mk3", 5, 445, 14.0F, 14.0F, 18);
	public static final ToolMaterial MATERIAL_REINFORCED_COBBLESTONE_MK4 = EnumHelper.addToolMaterial("material_reinforced_cobblestone_mk4", 8, 668, 21.0F, 23.0F, 27);
	public static final ToolMaterial MATERIAL_REINFORCED_IRON_INGOT_MK1 = EnumHelper.addToolMaterial("material_reinforced_iron_ingot_mk1", 4, 476, 11.0F, 7.0F, 27);
	public static final ToolMaterial MATERIAL_REINFORCED_IRON_INGOT_MK2 = EnumHelper.addToolMaterial("material_reinforced_iron_ingot_mk2", 8, 905, 21.0F, 17.0F, 51);
	public static final ToolMaterial MATERIAL_REINFORCED_IRON_INGOT_MK3 = EnumHelper.addToolMaterial("material_reinforced_iron_ingot_mk3", 15, 1720, 40.0F, 36.0F, 97);
	public static final ToolMaterial MATERIAL_REINFORCED_IRON_INGOT_MK4 = EnumHelper.addToolMaterial("material_reinforced_iron_ingot_mk4", 29, 3269, 76.0F, 72.0F, 184);
	public static final ToolMaterial MATERIAL_REINFORCED_GOLD_INGOT_MK1 = EnumHelper.addToolMaterial("material_reinforced_gold_ingot_mk1", 0, 39, 14.0F, 1.0F, 26);
	public static final ToolMaterial MATERIAL_REINFORCED_GOLD_INGOT_MK2 = EnumHelper.addToolMaterial("material_reinforced_gold_ingot_mk2", 0, 47, 17.0F, 2.0F, 31);
	public static final ToolMaterial MATERIAL_REINFORCED_GOLD_INGOT_MK3 = EnumHelper.addToolMaterial("material_reinforced_gold_ingot_mk3", 0, 57, 20.0F, 3.0F, 37);
	public static final ToolMaterial MATERIAL_REINFORCED_GOLD_INGOT_MK4 = EnumHelper.addToolMaterial("material_reinforced_gold_ingot_mk4", 0, 69, 24.0F, 4.0F, 44);
	public static final ToolMaterial MATERIAL_REINFORCED_DIAMOND_MK1 = EnumHelper.addToolMaterial("material_reinforced_diamond_mk1", 8, 3904, 20.0F, 14.0F, 25);
	public static final ToolMaterial MATERIAL_REINFORCED_DIAMOND_MK2 = EnumHelper.addToolMaterial("material_reinforced_diamond_mk2", 20, 9762, 50.0F, 41.0F, 63);
	public static final ToolMaterial MATERIAL_REINFORCED_DIAMOND_MK3 = EnumHelper.addToolMaterial("material_reinforced_diamond_mk3", 50, 24407, 125.0F, 109.0F, 158);
	public static final ToolMaterial MATERIAL_REINFORCED_DIAMOND_MK4 = EnumHelper.addToolMaterial("material_reinforced_diamond_mk4", 125, 61019, 313.0F, 279.0F, 395);
	public static final ToolMaterial MATERIAL_EMERALD = EnumHelper.addToolMaterial("material_emerald", 4, 2399, 14.0F, 4.0F, 18);
	public static final ToolMaterial MATERIAL_REINFORCED_EMERALD_MK1 = EnumHelper.addToolMaterial("material_reinforced_emerald_mk1", 11, 6479, 38.0F, 18.0F, 49);
	public static final ToolMaterial MATERIAL_REINFORCED_EMERALD_MK2 = EnumHelper.addToolMaterial("material_reinforced_emerald_mk2", 30, 17495, 103.0F, 55.0F, 132);
	public static final ToolMaterial MATERIAL_REINFORCED_EMERALD_MK3 = EnumHelper.addToolMaterial("material_reinforced_emerald_mk3", 81, 47238, 278.0F, 155.0F, 356);
	public static final ToolMaterial MATERIAL_REINFORCED_EMERALD_MK4 = EnumHelper.addToolMaterial("material_reinforced_emerald_mk4", 219, 127544, 751.0F, 425.0F, 961);
	public static final ToolMaterial MATERIAL_REDSTONE_INGOT = EnumHelper.addToolMaterial("material_redstone_ingot", 2, 599, 20.0F, 2.0F, 12);
	public static final ToolMaterial MATERIAL_REINFORCED_REDSTONE_INGOT_MK1 = EnumHelper.addToolMaterial("material_reinforced_redstone_ingot_mk1", 3, 1019, 34.0F, 6.0F, 20);
	public static final ToolMaterial MATERIAL_REINFORCED_REDSTONE_INGOT_MK2 = EnumHelper.addToolMaterial("material_reinforced_redstone_ingot_mk2", 5, 1733, 58.0F, 13.0F, 34);
	public static final ToolMaterial MATERIAL_REINFORCED_REDSTONE_INGOT_MK3 = EnumHelper.addToolMaterial("material_reinforced_redstone_ingot_mk3", 9, 2947, 99.0F, 25.0F, 58);
	public static final ToolMaterial MATERIAL_REINFORCED_REDSTONE_INGOT_MK4 = EnumHelper.addToolMaterial("material_reinforced_redstone_ingot_mk4", 15, 5011, 168.0F, 45.0F, 99);
	public static final ToolMaterial MATERIAL_LAPIS_INGOT = EnumHelper.addToolMaterial("material_lapis_ingot", 2, 239, 6.0F, 2.0F, 40);
	public static final ToolMaterial MATERIAL_REINFORCED_LAPIS_INGOT_MK1 = EnumHelper.addToolMaterial("material_reinforced_lapis_ingot_mk1", 3, 335, 8.0F, 4.0F, 56);
	public static final ToolMaterial MATERIAL_REINFORCED_LAPIS_INGOT_MK2 = EnumHelper.addToolMaterial("material_reinforced_lapis_ingot_mk2", 4, 469, 11.0F, 7.0F, 78);
	public static final ToolMaterial MATERIAL_REINFORCED_LAPIS_INGOT_MK3 = EnumHelper.addToolMaterial("material_reinforced_lapis_ingot_mk3", 6, 657, 15.0F, 11.0F, 109);
	public static final ToolMaterial MATERIAL_REINFORCED_LAPIS_INGOT_MK4 = EnumHelper.addToolMaterial("material_reinforced_lapis_ingot_mk4", 8, 920, 21.0F, 17.0F, 153);
	public static final ArmorMaterial ARMOR_MATERIAL_REINFORCED_IRON_INGOT_MK1 = EnumHelper.addArmorMaterial("armor_material_reinforced_iron_ingot_mk1", Reference.MOD_ID + ":reinforced_iron_ingot_armor_mk1", 29, new int[]{4, 10, 11, 4}, 17, SoundEvents.ITEM_ARMOR_EQUIP_IRON, 0.0F);
	public static final ArmorMaterial ARMOR_MATERIAL_REINFORCED_IRON_INGOT_MK2 = EnumHelper.addArmorMaterial("armor_material_reinforced_iron_ingot_mk2", Reference.MOD_ID + ":reinforced_iron_ingot_armor_mk2", 55, new int[]{8, 19, 21, 8}, 32, SoundEvents.ITEM_ARMOR_EQUIP_IRON, 0.0F);
	public static final ArmorMaterial ARMOR_MATERIAL_REINFORCED_IRON_INGOT_MK3 = EnumHelper.addArmorMaterial("armor_material_reinforced_iron_ingot_mk3", Reference.MOD_ID + ":reinforced_iron_ingot_armor_mk3", 105, new int[]{15, 36, 40, 15}, 60, SoundEvents.ITEM_ARMOR_EQUIP_IRON, 0.0F);
	public static final ArmorMaterial ARMOR_MATERIAL_REINFORCED_IRON_INGOT_MK4 = EnumHelper.addArmorMaterial("armor_material_reinforced_iron_ingot_mk4", Reference.MOD_ID + ":reinforced_iron_ingot_armor_mk4", 200, new int[]{29, 68, 76, 29}, 114, SoundEvents.ITEM_ARMOR_EQUIP_IRON, 0.0F);
	public static final ArmorMaterial ARMOR_MATERIAL_REINFORCED_GOLD_INGOT_MK1 = EnumHelper.addArmorMaterial("armor_material_reinforced_gold_ingot_mk1", Reference.MOD_ID + ":reinforced_gold_ingot_armor_mk1", 8, new int[]{1, 4, 6, 2}, 30, SoundEvents.ITEM_ARMOR_EQUIP_GOLD, 0.0F);
	public static final ArmorMaterial ARMOR_MATERIAL_REINFORCED_GOLD_INGOT_MK2 = EnumHelper.addArmorMaterial("armor_material_reinforced_gold_ingot_mk2", Reference.MOD_ID + ":reinforced_gold_ingot_armor_mk2", 10, new int[]{1, 5, 7, 2}, 36, SoundEvents.ITEM_ARMOR_EQUIP_GOLD, 0.0F);
	public static final ArmorMaterial ARMOR_MATERIAL_REINFORCED_GOLD_INGOT_MK3 = EnumHelper.addArmorMaterial("armor_material_reinforced_gold_ingot_mk3", Reference.MOD_ID + ":reinforced_gold_ingot_armor_mk3", 12, new int[]{1, 6, 8, 2}, 43, SoundEvents.ITEM_ARMOR_EQUIP_GOLD, 0.0F);
	public static final ArmorMaterial ARMOR_MATERIAL_REINFORCED_GOLD_INGOT_MK4 = EnumHelper.addArmorMaterial("armor_material_reinforced_gold_ingot_mk4", Reference.MOD_ID + ":reinforced_gold_ingot_armor_mk4", 14, new int[]{1, 7, 10, 2}, 114, SoundEvents.ITEM_ARMOR_EQUIP_GOLD, 0.0F);
	public static final ArmorMaterial ARMOR_MATERIAL_REINFORCED_DIAMOND_MK1 = EnumHelper.addArmorMaterial("armor_material_reinforced_diamond_mk1", Reference.MOD_ID + ":reinforced_diamond_armor_mk1", 83, new int[]{8, 15, 20, 8}, 25, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 5.0F);
	public static final ArmorMaterial ARMOR_MATERIAL_REINFORCED_DIAMOND_MK2 = EnumHelper.addArmorMaterial("armor_material_reinforced_diamond_mk2", Reference.MOD_ID + ":reinforced_diamond_armor_mk2", 208, new int[]{20, 38, 50, 20}, 63, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 13.0F);
	public static final ArmorMaterial ARMOR_MATERIAL_REINFORCED_DIAMOND_MK3 = EnumHelper.addArmorMaterial("armor_material_reinforced_diamond_mk3", Reference.MOD_ID + ":reinforced_diamond_armor_mk3", 520, new int[]{50, 95, 125, 50}, 158, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 33.0F);
	public static final ArmorMaterial ARMOR_MATERIAL_REINFORCED_DIAMOND_MK4 = EnumHelper.addArmorMaterial("armor_material_reinforced_diamond_mk4", Reference.MOD_ID + ":reinforced_diamond_armor_mk4", 1300, new int[]{125, 238, 313, 125}, 395, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 83.0F);
	public static final ArmorMaterial ARMOR_MATERIAL_EMERALD = EnumHelper.addArmorMaterial("armor_material_emerald", Reference.MOD_ID + ":emerald_armor", 40, new int[]{5, 9, 11, 5}, 20, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 3.0F);
	public static final ArmorMaterial ARMOR_MATERIAL_REINFORCED_EMERALD_MK1 = EnumHelper.addArmorMaterial("armor_material_reinforced_emerald_mk1", Reference.MOD_ID + ":reinforced_emerald_armor_mk1", 108, new int[]{14, 24, 30, 14}, 54, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 8.0F);
	public static final ArmorMaterial ARMOR_MATERIAL_REINFORCED_EMERALD_MK2 = EnumHelper.addArmorMaterial("armor_material_reinforced_emerald_mk2", Reference.MOD_ID + ":reinforced_emerald_armor_mk2", 292, new int[]{38, 65, 81, 38}, 146, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 22.0F);
	public static final ArmorMaterial ARMOR_MATERIAL_REINFORCED_EMERALD_MK3 = EnumHelper.addArmorMaterial("armor_material_reinforced_emerald_mk3", Reference.MOD_ID + ":reinforced_emerald_armor_mk3", 788, new int[]{103, 176, 219, 103}, 394, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 59.0F);
	public static final ArmorMaterial ARMOR_MATERIAL_REINFORCED_EMERALD_MK4 = EnumHelper.addArmorMaterial("armor_material_reinforced_emerald_mk4", Reference.MOD_ID + ":reinforced_emerald_armor_mk4", 2128, new int[]{278, 475, 591, 278}, 1064, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 159.0F);
	public static final ArmorMaterial ARMOR_MATERIAL_REDSTONE_INGOT = EnumHelper.addArmorMaterial("armor_material_redstone_ingot", Reference.MOD_ID + ":redstone_armor", 18, new int[]{4, 8, 9, 4}, 12, SoundEvents.ITEM_ARMOR_EQUIP_IRON, 1.0F);
	public static final ArmorMaterial ARMOR_MATERIAL_REINFORCED_REDSTONE_INGOT_MK1 = EnumHelper.addArmorMaterial("armor_material_reinforced_redstone_ingot_mk1", Reference.MOD_ID + ":reinforced_redstone_armor_mk1", 31, new int[]{7, 14, 15, 7}, 20, SoundEvents.ITEM_ARMOR_EQUIP_IRON, 2.0F);
	public static final ArmorMaterial ARMOR_MATERIAL_REINFORCED_REDSTONE_INGOT_MK2 = EnumHelper.addArmorMaterial("armor_material_reinforced_redstone_ingot_mk2", Reference.MOD_ID + ":reinforced_redstone_armor_mk2", 84, new int[]{12, 24, 26, 12}, 34, SoundEvents.ITEM_ARMOR_EQUIP_IRON, 3.0F);
	public static final ArmorMaterial ARMOR_MATERIAL_REINFORCED_REDSTONE_INGOT_MK3 = EnumHelper.addArmorMaterial("armor_material_reinforced_redstone_ingot_mk3", Reference.MOD_ID + ":reinforced_redstone_armor_mk3", 227, new int[]{20, 41, 44, 20}, 58, SoundEvents.ITEM_ARMOR_EQUIP_IRON, 5.0F);
	public static final ArmorMaterial ARMOR_MATERIAL_REINFORCED_REDSTONE_INGOT_MK4 = EnumHelper.addArmorMaterial("armor_material_reinforced_redstone_ingot_mk4", Reference.MOD_ID + ":reinforced_redstone_armor_mk4", 613, new int[]{34, 70, 75, 34}, 99, SoundEvents.ITEM_ARMOR_EQUIP_IRON, 9.0F);
	public static final ArmorMaterial ARMOR_MATERIAL_LAPIS_INGOT = EnumHelper.addArmorMaterial("armor_material_lapis_ingot", Reference.MOD_ID + ":lapis_armor", 8, new int[]{2, 3, 5, 2}, 40, SoundEvents.ITEM_ARMOR_EQUIP_IRON, 0.0F);
	public static final ArmorMaterial ARMOR_MATERIAL_REINFORCED_LAPIS_INGOT_MK1 = EnumHelper.addArmorMaterial("armor_material_reinforced_lapis_ingot_mk1", Reference.MOD_ID + ":reinforced_lapis_armor_mk1", 11, new int[]{3, 4, 7, 3}, 56, SoundEvents.ITEM_ARMOR_EQUIP_IRON, 0.0F);
	public static final ArmorMaterial ARMOR_MATERIAL_REINFORCED_LAPIS_INGOT_MK2 = EnumHelper.addArmorMaterial("armor_material_reinforced_lapis_ingot_mk2", Reference.MOD_ID + ":reinforced_lapis_armor_mk2", 15, new int[]{4, 6, 10, 4}, 78, SoundEvents.ITEM_ARMOR_EQUIP_IRON, 0.0F);
	public static final ArmorMaterial ARMOR_MATERIAL_REINFORCED_LAPIS_INGOT_MK3 = EnumHelper.addArmorMaterial("armor_material_reinforced_lapis_ingot_mk3", Reference.MOD_ID + ":reinforced_lapis_armor_mk3", 21, new int[]{6, 8, 14, 6}, 109, SoundEvents.ITEM_ARMOR_EQUIP_IRON, 0.0F);
	public static final ArmorMaterial ARMOR_MATERIAL_REINFORCED_LAPIS_INGOT_MK4 = EnumHelper.addArmorMaterial("armor_material_reinforced_lapis_ingot_mk4", Reference.MOD_ID + ":reinforced_lapis_armor_mk4", 29, new int[]{8, 11, 20, 8}, 153, SoundEvents.ITEM_ARMOR_EQUIP_IRON, 0.0F);
	
	//Items
	public static final Item REINFORCED_IRON_INGOT_MK1 = new ItemBase("reinforced_iron_ingot_mk1");
	public static final Item REINFORCED_IRON_INGOT_MK2 = new ItemBase("reinforced_iron_ingot_mk2");
	public static final Item REINFORCED_IRON_INGOT_MK3 = new ItemBase("reinforced_iron_ingot_mk3");
	public static final Item REINFORCED_IRON_INGOT_MK4 = new ItemBase("reinforced_iron_ingot_mk4");
	public static final Item REINFORCED_GOLD_INGOT_MK1 = new ItemBase("reinforced_gold_ingot_mk1");
	public static final Item REINFORCED_GOLD_INGOT_MK2 = new ItemBase("reinforced_gold_ingot_mk2");
	public static final Item REINFORCED_GOLD_INGOT_MK3 = new ItemBase("reinforced_gold_ingot_mk3");
	public static final Item REINFORCED_GOLD_INGOT_MK4 = new ItemBase("reinforced_gold_ingot_mk4");
	public static final Item REINFORCED_DIAMOND_MK1 = new ItemBase("reinforced_diamond_mk1");
	public static final Item REINFORCED_DIAMOND_MK2 = new ItemBase("reinforced_diamond_mk2");
	public static final Item REINFORCED_DIAMOND_MK3 = new ItemBase("reinforced_diamond_mk3");
	public static final Item REINFORCED_DIAMOND_MK4 = new ItemBase("reinforced_diamond_mk4");
	public static final Item REINFORCED_EMERALD_MK1 = new ItemBase("reinforced_emerald_mk1");
	public static final Item REINFORCED_EMERALD_MK2 = new ItemBase("reinforced_emerald_mk2");
	public static final Item REINFORCED_EMERALD_MK3 = new ItemBase("reinforced_emerald_mk3");
	public static final Item REINFORCED_EMERALD_MK4 = new ItemBase("reinforced_emerald_mk4");
	public static final Item REDSTONE_INGOT = new ItemBase("redstone_ingot");
	public static final Item REINFORCED_REDSTONE_INGOT_MK1 = new ItemBase("reinforced_redstone_ingot_mk1");
	public static final Item REINFORCED_REDSTONE_INGOT_MK2 = new ItemBase("reinforced_redstone_ingot_mk2");
	public static final Item REINFORCED_REDSTONE_INGOT_MK3 = new ItemBase("reinforced_redstone_ingot_mk3");
	public static final Item REINFORCED_REDSTONE_INGOT_MK4 = new ItemBase("reinforced_redstone_ingot_mk4");
	public static final Item LAPIS_INGOT = new ItemBase("lapis_ingot");
	public static final Item REINFORCED_LAPIS_INGOT_MK1 = new ItemBase("reinforced_lapis_ingot_mk1");
	public static final Item REINFORCED_LAPIS_INGOT_MK2 = new ItemBase("reinforced_lapis_ingot_mk2");
	public static final Item REINFORCED_LAPIS_INGOT_MK3 = new ItemBase("reinforced_lapis_ingot_mk3");
	public static final Item REINFORCED_LAPIS_INGOT_MK4 = new ItemBase("reinforced_lapis_ingot_mk4");
	
	//Tools
	public static final ItemSword REINFORCED_WOODEN_PLANKS_MK1_SWORD = new ToolSword("reinforced_wooden_planks_mk1_sword", MATERIAL_REINFORCED_WOODEN_PLANKS_MK1);
	public static final ItemSword REINFORCED_WOODEN_PLANKS_MK2_SWORD = new ToolSword("reinforced_wooden_planks_mk2_sword", MATERIAL_REINFORCED_WOODEN_PLANKS_MK2);
	public static final ItemSword REINFORCED_WOODEN_PLANKS_MK3_SWORD = new ToolSword("reinforced_wooden_planks_mk3_sword", MATERIAL_REINFORCED_WOODEN_PLANKS_MK3);
	public static final ItemSword REINFORCED_WOODEN_PLANKS_MK4_SWORD = new ToolSword("reinforced_wooden_planks_mk4_sword", MATERIAL_REINFORCED_WOODEN_PLANKS_MK4);
	public static final ItemSword REINFORCED_COBBLESTONE_MK1_SWORD = new ToolSword("reinforced_cobblestone_mk1_sword", MATERIAL_REINFORCED_COBBLESTONE_MK1);
	public static final ItemSword REINFORCED_COBBLESTONE_MK2_SWORD = new ToolSword("reinforced_cobblestone_mk2_sword", MATERIAL_REINFORCED_COBBLESTONE_MK2);
	public static final ItemSword REINFORCED_COBBLESTONE_MK3_SWORD = new ToolSword("reinforced_cobblestone_mk3_sword", MATERIAL_REINFORCED_COBBLESTONE_MK3);
	public static final ItemSword REINFORCED_COBBLESTONE_MK4_SWORD = new ToolSword("reinforced_cobblestone_mk4_sword", MATERIAL_REINFORCED_COBBLESTONE_MK4);
	public static final ItemSword REINFORCED_IRON_INGOT_MK1_SWORD = new ToolSword("reinforced_iron_ingot_mk1_sword", MATERIAL_REINFORCED_IRON_INGOT_MK1);
	public static final ItemSword REINFORCED_IRON_INGOT_MK2_SWORD = new ToolSword("reinforced_iron_ingot_mk2_sword", MATERIAL_REINFORCED_IRON_INGOT_MK2);
	public static final ItemSword REINFORCED_IRON_INGOT_MK3_SWORD = new ToolSword("reinforced_iron_ingot_mk3_sword", MATERIAL_REINFORCED_IRON_INGOT_MK3);
	public static final ItemSword REINFORCED_IRON_INGOT_MK4_SWORD = new ToolSword("reinforced_iron_ingot_mk4_sword", MATERIAL_REINFORCED_IRON_INGOT_MK4);
	public static final ItemSword REINFORCED_GOLD_INGOT_MK1_SWORD = new ToolSword("reinforced_gold_ingot_mk1_sword", MATERIAL_REINFORCED_GOLD_INGOT_MK1);
	public static final ItemSword REINFORCED_GOLD_INGOT_MK2_SWORD = new ToolSword("reinforced_gold_ingot_mk2_sword", MATERIAL_REINFORCED_GOLD_INGOT_MK2);
	public static final ItemSword REINFORCED_GOLD_INGOT_MK3_SWORD = new ToolSword("reinforced_gold_ingot_mk3_sword", MATERIAL_REINFORCED_GOLD_INGOT_MK3);
	public static final ItemSword REINFORCED_GOLD_INGOT_MK4_SWORD = new ToolSword("reinforced_gold_ingot_mk4_sword", MATERIAL_REINFORCED_GOLD_INGOT_MK4);
	public static final ItemSword REINFORCED_DIAMOND_MK1_SWORD = new ToolSword("reinforced_diamond_mk1_sword", MATERIAL_REINFORCED_DIAMOND_MK1);
	public static final ItemSword REINFORCED_DIAMOND_MK2_SWORD = new ToolSword("reinforced_diamond_mk2_sword", MATERIAL_REINFORCED_DIAMOND_MK2);
	public static final ItemSword REINFORCED_DIAMOND_MK3_SWORD = new ToolSword("reinforced_diamond_mk3_sword", MATERIAL_REINFORCED_DIAMOND_MK3);
	public static final ItemSword REINFORCED_DIAMOND_MK4_SWORD = new ToolSword("reinforced_diamond_mk4_sword", MATERIAL_REINFORCED_DIAMOND_MK4);
	public static final ItemSword EMERALD_SWORD = new ToolSword("emerald_sword", MATERIAL_EMERALD);
	public static final ItemSword REINFORCED_EMERALD_MK1_SWORD = new ToolSword("reinforced_emerald_mk1_sword", MATERIAL_REINFORCED_EMERALD_MK1);
	public static final ItemSword REINFORCED_EMERALD_MK2_SWORD = new ToolSword("reinforced_emerald_mk2_sword", MATERIAL_REINFORCED_EMERALD_MK2);
	public static final ItemSword REINFORCED_EMERALD_MK3_SWORD = new ToolSword("reinforced_emerald_mk3_sword", MATERIAL_REINFORCED_EMERALD_MK3);
	public static final ItemSword REINFORCED_EMERALD_MK4_SWORD = new ToolSword("reinforced_emerald_mk4_sword", MATERIAL_REINFORCED_EMERALD_MK4);
	public static final ItemSword REDSTONE_INGOT_SWORD = new ToolSword("redstone_ingot_sword", MATERIAL_REDSTONE_INGOT);
	public static final ItemSword REINFORCED_REDSTONE_INGOT_MK1_SWORD = new ToolSword("reinforced_redstone_ingot_mk1_sword", MATERIAL_REINFORCED_REDSTONE_INGOT_MK1);
	public static final ItemSword REINFORCED_REDSTONE_INGOT_MK2_SWORD = new ToolSword("reinforced_redstone_ingot_mk2_sword", MATERIAL_REINFORCED_REDSTONE_INGOT_MK2);
	public static final ItemSword REINFORCED_REDSTONE_INGOT_MK3_SWORD = new ToolSword("reinforced_redstone_ingot_mk3_sword", MATERIAL_REINFORCED_REDSTONE_INGOT_MK3);
	public static final ItemSword REINFORCED_REDSTONE_INGOT_MK4_SWORD = new ToolSword("reinforced_redstone_ingot_mk4_sword", MATERIAL_REINFORCED_REDSTONE_INGOT_MK4);
	public static final ItemSword LAPIS_INGOT_SWORD = new ToolSword("lapis_ingot_sword", MATERIAL_LAPIS_INGOT);
	public static final ItemSword REINFORCED_LAPIS_INGOT_MK1_SWORD = new ToolSword("reinforced_lapis_ingot_mk1_sword", MATERIAL_REINFORCED_LAPIS_INGOT_MK1);
	public static final ItemSword REINFORCED_LAPIS_INGOT_MK2_SWORD = new ToolSword("reinforced_lapis_ingot_mk2_sword", MATERIAL_REINFORCED_LAPIS_INGOT_MK2);
	public static final ItemSword REINFORCED_LAPIS_INGOT_MK3_SWORD = new ToolSword("reinforced_lapis_ingot_mk3_sword", MATERIAL_REINFORCED_LAPIS_INGOT_MK3);
	public static final ItemSword REINFORCED_LAPIS_INGOT_MK4_SWORD = new ToolSword("reinforced_lapis_ingot_mk4_sword", MATERIAL_REINFORCED_LAPIS_INGOT_MK4);
	public static final ItemAxe REINFORCED_WOODEN_PLANKS_MK1_AXE = new ToolAxe("reinforced_wooden_planks_mk1_axe", MATERIAL_REINFORCED_WOODEN_PLANKS_MK1, 4);
	public static final ItemAxe REINFORCED_WOODEN_PLANKS_MK2_AXE = new ToolAxe("reinforced_wooden_planks_mk2_axe", MATERIAL_REINFORCED_WOODEN_PLANKS_MK2, 6);
	public static final ItemAxe REINFORCED_WOODEN_PLANKS_MK3_AXE = new ToolAxe("reinforced_wooden_planks_mk3_axe", MATERIAL_REINFORCED_WOODEN_PLANKS_MK3, 8);
	public static final ItemAxe REINFORCED_WOODEN_PLANKS_MK4_AXE = new ToolAxe("reinforced_wooden_planks_mk4_axe", MATERIAL_REINFORCED_WOODEN_PLANKS_MK4, 11);
	public static final ItemAxe REINFORCED_COBBLESTONE_MK1_AXE = new ToolAxe("reinforced_cobblestone_mk1_axe", MATERIAL_REINFORCED_COBBLESTONE_MK1, 7);
	public static final ItemAxe REINFORCED_COBBLESTONE_MK2_AXE = new ToolAxe("reinforced_cobblestone_mk2_axe", MATERIAL_REINFORCED_COBBLESTONE_MK2, 11);
	public static final ItemAxe REINFORCED_COBBLESTONE_MK3_AXE = new ToolAxe("reinforced_cobblestone_mk3_axe", MATERIAL_REINFORCED_COBBLESTONE_MK3, 17);
	public static final ItemAxe REINFORCED_COBBLESTONE_MK4_AXE = new ToolAxe("reinforced_cobblestone_mk4_axe", MATERIAL_REINFORCED_COBBLESTONE_MK4, 26);
	public static final ItemAxe REINFORCED_IRON_INGOT_MK1_AXE = new ToolAxe("reinforced_iron_ingot_mk1_axe", MATERIAL_REINFORCED_IRON_INGOT_MK1, 10);
	public static final ItemAxe REINFORCED_IRON_INGOT_MK2_AXE = new ToolAxe("reinforced_iron_ingot_mk2_axe", MATERIAL_REINFORCED_IRON_INGOT_MK2, 20);
	public static final ItemAxe REINFORCED_IRON_INGOT_MK3_AXE = new ToolAxe("reinforced_iron_ingot_mk3_axe", MATERIAL_REINFORCED_IRON_INGOT_MK3, 39);
	public static final ItemAxe REINFORCED_IRON_INGOT_MK4_AXE = new ToolAxe("reinforced_iron_ingot_mk4_axe", MATERIAL_REINFORCED_IRON_INGOT_MK4, 75);
	public static final ItemAxe REINFORCED_GOLD_INGOT_MK1_AXE = new ToolAxe("reinforced_gold_ingot_mk1_axe", MATERIAL_REINFORCED_GOLD_INGOT_MK1, 4);
	public static final ItemAxe REINFORCED_GOLD_INGOT_MK2_AXE = new ToolAxe("reinforced_gold_ingot_mk2_axe", MATERIAL_REINFORCED_GOLD_INGOT_MK2, 5);
	public static final ItemAxe REINFORCED_GOLD_INGOT_MK3_AXE = new ToolAxe("reinforced_gold_ingot_mk3_axe", MATERIAL_REINFORCED_GOLD_INGOT_MK3, 6);
	public static final ItemAxe REINFORCED_GOLD_INGOT_MK4_AXE = new ToolAxe("reinforced_gold_ingot_mk4_axe", MATERIAL_REINFORCED_GOLD_INGOT_MK4, 7);
	public static final ItemAxe REINFORCED_DIAMOND_MK1_AXE = new ToolAxe("reinforced_diamond_mk1_axe", MATERIAL_REINFORCED_DIAMOND_MK1, 17);
	public static final ItemAxe REINFORCED_DIAMOND_MK2_AXE = new ToolAxe("reinforced_diamond_mk2_axe", MATERIAL_REINFORCED_DIAMOND_MK2, 44);
	public static final ItemAxe REINFORCED_DIAMOND_MK3_AXE = new ToolAxe("reinforced_diamond_mk3_axe", MATERIAL_REINFORCED_DIAMOND_MK3, 112);
	public static final ItemAxe REINFORCED_DIAMOND_MK4_AXE = new ToolAxe("reinforced_diamond_mk4_axe", MATERIAL_REINFORCED_DIAMOND_MK4, 282);
	public static final ItemAxe EMERALD_AXE = new ToolAxe("emerald_axe", MATERIAL_EMERALD, 7);
	public static final ItemAxe REINFORCED_EMERALD_MK1_AXE = new ToolAxe("reinforced_emerald_mk1_axe", MATERIAL_REINFORCED_EMERALD_MK1, 21);
	public static final ItemAxe REINFORCED_EMERALD_MK2_AXE = new ToolAxe("reinforced_emerald_mk2_axe", MATERIAL_REINFORCED_EMERALD_MK2, 58);
	public static final ItemAxe REINFORCED_EMERALD_MK3_AXE = new ToolAxe("reinforced_emerald_mk3_axe", MATERIAL_REINFORCED_EMERALD_MK3, 158);
	public static final ItemAxe REINFORCED_EMERALD_MK4_AXE = new ToolAxe("reinforced_emerald_mk4_axe", MATERIAL_REINFORCED_EMERALD_MK4, 428);
	public static final ItemAxe REDSTONE_INGOT_AXE = new ToolAxe("redstone_ingot_axe", MATERIAL_REDSTONE_INGOT, 5);
	public static final ItemAxe REINFORCED_REDSTONE_INGOT_MK1_AXE = new ToolAxe("reinforced_redstone_ingot_mk1_axe", MATERIAL_REINFORCED_REDSTONE_INGOT_MK1, 9);
	public static final ItemAxe REINFORCED_REDSTONE_INGOT_MK2_AXE = new ToolAxe("reinforced_redstone_ingot_mk2_axe", MATERIAL_REINFORCED_REDSTONE_INGOT_MK2, 16);
	public static final ItemAxe REINFORCED_REDSTONE_INGOT_MK3_AXE = new ToolAxe("reinforced_redstone_ingot_mk3_axe", MATERIAL_REINFORCED_REDSTONE_INGOT_MK3, 28);
	public static final ItemAxe REINFORCED_REDSTONE_INGOT_MK4_AXE = new ToolAxe("reinforced_redstone_ingot_mk4_axe", MATERIAL_REINFORCED_REDSTONE_INGOT_MK4, 48);
	public static final ItemAxe LAPIS_INGOT_AXE = new ToolAxe("lapis_ingot_axe", MATERIAL_LAPIS_INGOT, 5);
	public static final ItemAxe REINFORCED_LAPIS_INGOT_MK1_AXE = new ToolAxe("reinforced_lapis_ingot_mk1_axe", MATERIAL_REINFORCED_LAPIS_INGOT_MK1, 7);
	public static final ItemAxe REINFORCED_LAPIS_INGOT_MK2_AXE = new ToolAxe("reinforced_lapis_ingot_mk2_axe", MATERIAL_REINFORCED_LAPIS_INGOT_MK2, 10);
	public static final ItemAxe REINFORCED_LAPIS_INGOT_MK3_AXE = new ToolAxe("reinforced_lapis_ingot_mk3_axe", MATERIAL_REINFORCED_LAPIS_INGOT_MK3, 14);
	public static final ItemAxe REINFORCED_LAPIS_INGOT_MK4_AXE = new ToolAxe("reinforced_lapis_ingot_mk4_axe", MATERIAL_REINFORCED_LAPIS_INGOT_MK4, 20);
	public static final ItemPickaxe REINFORCED_WOODEN_PLANKS_MK1_PICKAXE = new ToolPickaxe("reinforced_wooden_planks_mk1_pickaxe", MATERIAL_REINFORCED_WOODEN_PLANKS_MK1);
	public static final ItemPickaxe REINFORCED_WOODEN_PLANKS_MK2_PICKAXE = new ToolPickaxe("reinforced_wooden_planks_mk2_pickaxe", MATERIAL_REINFORCED_WOODEN_PLANKS_MK2);
	public static final ItemPickaxe REINFORCED_WOODEN_PLANKS_MK3_PICKAXE = new ToolPickaxe("reinforced_wooden_planks_mk3_pickaxe", MATERIAL_REINFORCED_WOODEN_PLANKS_MK3);
	public static final ItemPickaxe REINFORCED_WOODEN_PLANKS_MK4_PICKAXE = new ToolPickaxe("reinforced_wooden_planks_mk4_pickaxe", MATERIAL_REINFORCED_WOODEN_PLANKS_MK4);
	public static final ItemPickaxe REINFORCED_COBBLESTONE_MK1_PICKAXE = new ToolPickaxe("reinforced_cobblestone_mk1_pickaxe", MATERIAL_REINFORCED_COBBLESTONE_MK1);
	public static final ItemPickaxe REINFORCED_COBBLESTONE_MK2_PICKAXE = new ToolPickaxe("reinforced_cobblestone_mk2_pickaxe", MATERIAL_REINFORCED_COBBLESTONE_MK2);
	public static final ItemPickaxe REINFORCED_COBBLESTONE_MK3_PICKAXE = new ToolPickaxe("reinforced_cobblestone_mk3_pickaxe", MATERIAL_REINFORCED_COBBLESTONE_MK3);
	public static final ItemPickaxe REINFORCED_COBBLESTONE_MK4_PICKAXE = new ToolPickaxe("reinforced_cobblestone_mk4_pickaxe", MATERIAL_REINFORCED_COBBLESTONE_MK4);
	public static final ItemPickaxe REINFORCED_IRON_INGOT_MK1_PICKAXE = new ToolPickaxe("reinforced_iron_ingot_mk1_pickaxe", MATERIAL_REINFORCED_IRON_INGOT_MK1);
	public static final ItemPickaxe REINFORCED_IRON_INGOT_MK2_PICKAXE = new ToolPickaxe("reinforced_iron_ingot_mk2_pickaxe", MATERIAL_REINFORCED_IRON_INGOT_MK2);
	public static final ItemPickaxe REINFORCED_IRON_INGOT_MK3_PICKAXE = new ToolPickaxe("reinforced_iron_ingot_mk3_pickaxe", MATERIAL_REINFORCED_IRON_INGOT_MK3);
	public static final ItemPickaxe REINFORCED_IRON_INGOT_MK4_PICKAXE = new ToolPickaxe("reinforced_iron_ingot_mk4_pickaxe", MATERIAL_REINFORCED_IRON_INGOT_MK4);
	public static final ItemPickaxe REINFORCED_GOLD_INGOT_MK1_PICKAXE = new ToolPickaxe("reinforced_gold_ingot_mk1_pickaxe", MATERIAL_REINFORCED_GOLD_INGOT_MK1);
	public static final ItemPickaxe REINFORCED_GOLD_INGOT_MK2_PICKAXE = new ToolPickaxe("reinforced_gold_ingot_mk2_pickaxe", MATERIAL_REINFORCED_GOLD_INGOT_MK2);
	public static final ItemPickaxe REINFORCED_GOLD_INGOT_MK3_PICKAXE = new ToolPickaxe("reinforced_gold_ingot_mk3_pickaxe", MATERIAL_REINFORCED_GOLD_INGOT_MK3);
	public static final ItemPickaxe REINFORCED_GOLD_INGOT_MK4_PICKAXE = new ToolPickaxe("reinforced_gold_ingot_mk4_pickaxe", MATERIAL_REINFORCED_GOLD_INGOT_MK4);
	public static final ItemPickaxe REINFORCED_DIAMOND_MK1_PICKAXE = new ToolPickaxe("reinforced_diamond_mk1_pickaxe", MATERIAL_REINFORCED_DIAMOND_MK1);
	public static final ItemPickaxe REINFORCED_DIAMOND_MK2_PICKAXE = new ToolPickaxe("reinforced_diamond_mk2_pickaxe", MATERIAL_REINFORCED_DIAMOND_MK2);
	public static final ItemPickaxe REINFORCED_DIAMOND_MK3_PICKAXE = new ToolPickaxe("reinforced_diamond_mk3_pickaxe", MATERIAL_REINFORCED_DIAMOND_MK3);
	public static final ItemPickaxe REINFORCED_DIAMOND_MK4_PICKAXE = new ToolPickaxe("reinforced_diamond_mk4_pickaxe", MATERIAL_REINFORCED_DIAMOND_MK4);
	public static final ItemPickaxe EMERALD_PICKAXE = new ToolPickaxe("emerald_pickaxe", MATERIAL_EMERALD);
	public static final ItemPickaxe REINFORCED_EMERALD_MK1_PICKAXE = new ToolPickaxe("reinforced_emerald_mk1_pickaxe", MATERIAL_REINFORCED_EMERALD_MK1);
	public static final ItemPickaxe REINFORCED_EMERALD_MK2_PICKAXE = new ToolPickaxe("reinforced_emerald_mk2_pickaxe", MATERIAL_REINFORCED_EMERALD_MK2);
	public static final ItemPickaxe REINFORCED_EMERALD_MK3_PICKAXE = new ToolPickaxe("reinforced_emerald_mk3_pickaxe", MATERIAL_REINFORCED_EMERALD_MK3);
	public static final ItemPickaxe REINFORCED_EMERALD_MK4_PICKAXE = new ToolPickaxe("reinforced_emerald_mk4_pickaxe", MATERIAL_REINFORCED_EMERALD_MK4);
	public static final ItemPickaxe REDSTONE_INGOT_PICKAXE = new ToolPickaxe("redstone_ingot_pickaxe", MATERIAL_REDSTONE_INGOT);
	public static final ItemPickaxe REINFORCED_REDSTONE_INGOT_MK1_PICKAXE = new ToolPickaxe("reinforced_redstone_ingot_mk1_pickaxe", MATERIAL_REINFORCED_REDSTONE_INGOT_MK1);
	public static final ItemPickaxe REINFORCED_REDSTONE_INGOT_MK2_PICKAXE = new ToolPickaxe("reinforced_redstone_ingot_mk2_pickaxe", MATERIAL_REINFORCED_REDSTONE_INGOT_MK2);
	public static final ItemPickaxe REINFORCED_REDSTONE_INGOT_MK3_PICKAXE = new ToolPickaxe("reinforced_redstone_ingot_mk3_pickaxe", MATERIAL_REINFORCED_REDSTONE_INGOT_MK3);
	public static final ItemPickaxe REINFORCED_REDSTONE_INGOT_MK4_PICKAXE = new ToolPickaxe("reinforced_redstone_ingot_mk4_pickaxe", MATERIAL_REINFORCED_REDSTONE_INGOT_MK4);
	public static final ItemPickaxe LAPIS_INGOT_PICKAXE = new ToolPickaxe("lapis_ingot_pickaxe", MATERIAL_LAPIS_INGOT);
	public static final ItemPickaxe REINFORCED_LAPIS_INGOT_MK1_PICKAXE = new ToolPickaxe("reinforced_lapis_ingot_mk1_pickaxe", MATERIAL_REINFORCED_LAPIS_INGOT_MK1);
	public static final ItemPickaxe REINFORCED_LAPIS_INGOT_MK2_PICKAXE = new ToolPickaxe("reinforced_lapis_ingot_mk2_pickaxe", MATERIAL_REINFORCED_LAPIS_INGOT_MK2);
	public static final ItemPickaxe REINFORCED_LAPIS_INGOT_MK3_PICKAXE = new ToolPickaxe("reinforced_lapis_ingot_mk3_pickaxe", MATERIAL_REINFORCED_LAPIS_INGOT_MK3);
	public static final ItemPickaxe REINFORCED_LAPIS_INGOT_MK4_PICKAXE = new ToolPickaxe("reinforced_lapis_ingot_mk4_pickaxe", MATERIAL_REINFORCED_LAPIS_INGOT_MK4);
	public static final ItemSpade REINFORCED_WOODEN_PLANKS_MK1_SPADE = new ToolSpade("reinforced_wooden_planks_mk1_spade", MATERIAL_REINFORCED_WOODEN_PLANKS_MK1);
	public static final ItemSpade REINFORCED_WOODEN_PLANKS_MK2_SPADE = new ToolSpade("reinforced_wooden_planks_mk2_spade", MATERIAL_REINFORCED_WOODEN_PLANKS_MK2);
	public static final ItemSpade REINFORCED_WOODEN_PLANKS_MK3_SPADE = new ToolSpade("reinforced_wooden_planks_mk3_spade", MATERIAL_REINFORCED_WOODEN_PLANKS_MK3);
	public static final ItemSpade REINFORCED_WOODEN_PLANKS_MK4_SPADE = new ToolSpade("reinforced_wooden_planks_mk4_spade", MATERIAL_REINFORCED_WOODEN_PLANKS_MK4);
	public static final ItemSpade REINFORCED_COBBLESTONE_MK1_SPADE = new ToolSpade("reinforced_cobblestone_mk1_spade", MATERIAL_REINFORCED_COBBLESTONE_MK1);
	public static final ItemSpade REINFORCED_COBBLESTONE_MK2_SPADE = new ToolSpade("reinforced_cobblestone_mk2_spade", MATERIAL_REINFORCED_COBBLESTONE_MK2);
	public static final ItemSpade REINFORCED_COBBLESTONE_MK3_SPADE = new ToolSpade("reinforced_cobblestone_mk3_spade", MATERIAL_REINFORCED_COBBLESTONE_MK3);
	public static final ItemSpade REINFORCED_COBBLESTONE_MK4_SPADE = new ToolSpade("reinforced_cobblestone_mk4_spade", MATERIAL_REINFORCED_COBBLESTONE_MK4);
	public static final ItemSpade REINFORCED_IRON_INGOT_MK1_SPADE = new ToolSpade("reinforced_iron_ingot_mk1_spade", MATERIAL_REINFORCED_IRON_INGOT_MK1);
	public static final ItemSpade REINFORCED_IRON_INGOT_MK2_SPADE = new ToolSpade("reinforced_iron_ingot_mk2_spade", MATERIAL_REINFORCED_IRON_INGOT_MK2);
	public static final ItemSpade REINFORCED_IRON_INGOT_MK3_SPADE = new ToolSpade("reinforced_iron_ingot_mk3_spade", MATERIAL_REINFORCED_IRON_INGOT_MK3);
	public static final ItemSpade REINFORCED_IRON_INGOT_MK4_SPADE = new ToolSpade("reinforced_iron_ingot_mk4_spade", MATERIAL_REINFORCED_IRON_INGOT_MK4);
	public static final ItemSpade REINFORCED_GOLD_INGOT_MK1_SPADE = new ToolSpade("reinforced_gold_ingot_mk1_spade", MATERIAL_REINFORCED_GOLD_INGOT_MK1);
	public static final ItemSpade REINFORCED_GOLD_INGOT_MK2_SPADE = new ToolSpade("reinforced_gold_ingot_mk2_spade", MATERIAL_REINFORCED_GOLD_INGOT_MK2);
	public static final ItemSpade REINFORCED_GOLD_INGOT_MK3_SPADE = new ToolSpade("reinforced_gold_ingot_mk3_spade", MATERIAL_REINFORCED_GOLD_INGOT_MK3);
	public static final ItemSpade REINFORCED_GOLD_INGOT_MK4_SPADE = new ToolSpade("reinforced_gold_ingot_mk4_spade", MATERIAL_REINFORCED_GOLD_INGOT_MK4);
	public static final ItemSpade REINFORCED_DIAMOND_MK1_SPADE = new ToolSpade("reinforced_diamond_mk1_spade", MATERIAL_REINFORCED_DIAMOND_MK1);
	public static final ItemSpade REINFORCED_DIAMOND_MK2_SPADE = new ToolSpade("reinforced_diamond_mk2_spade", MATERIAL_REINFORCED_DIAMOND_MK2);
	public static final ItemSpade REINFORCED_DIAMOND_MK3_SPADE = new ToolSpade("reinforced_diamond_mk3_spade", MATERIAL_REINFORCED_DIAMOND_MK3);
	public static final ItemSpade REINFORCED_DIAMOND_MK4_SPADE = new ToolSpade("reinforced_diamond_mk4_spade", MATERIAL_REINFORCED_DIAMOND_MK4);
	public static final ItemSpade EMERALD_SPADE = new ToolSpade("emerald_spade", MATERIAL_EMERALD);
	public static final ItemSpade REINFORCED_EMERALD_MK1_SPADE = new ToolSpade("reinforced_emerald_mk1_spade", MATERIAL_REINFORCED_EMERALD_MK1);
	public static final ItemSpade REINFORCED_EMERALD_MK2_SPADE = new ToolSpade("reinforced_emerald_mk2_spade", MATERIAL_REINFORCED_EMERALD_MK2);
	public static final ItemSpade REINFORCED_EMERALD_MK3_SPADE = new ToolSpade("reinforced_emerald_mk3_spade", MATERIAL_REINFORCED_EMERALD_MK3);
	public static final ItemSpade REINFORCED_EMERALD_MK4_SPADE = new ToolSpade("reinforced_emerald_mk4_spade", MATERIAL_REINFORCED_EMERALD_MK4);
	public static final ItemSpade REDSTONE_INGOT_SPADE = new ToolSpade("redstone_ingot_spade", MATERIAL_REDSTONE_INGOT);
	public static final ItemSpade REINFORCED_REDSTONE_INGOT_MK1_SPADE = new ToolSpade("reinforced_redstone_ingot_mk1_spade", MATERIAL_REINFORCED_REDSTONE_INGOT_MK1);
	public static final ItemSpade REINFORCED_REDSTONE_INGOT_MK2_SPADE = new ToolSpade("reinforced_redstone_ingot_mk2_spade", MATERIAL_REINFORCED_REDSTONE_INGOT_MK2);
	public static final ItemSpade REINFORCED_REDSTONE_INGOT_MK3_SPADE = new ToolSpade("reinforced_redstone_ingot_mk3_spade", MATERIAL_REINFORCED_REDSTONE_INGOT_MK3);
	public static final ItemSpade REINFORCED_REDSTONE_INGOT_MK4_SPADE = new ToolSpade("reinforced_redstone_ingot_mk4_spade", MATERIAL_REINFORCED_REDSTONE_INGOT_MK4);
	public static final ItemSpade LAPIS_INGOT_SPADE = new ToolSpade("lapis_ingot_spade", MATERIAL_LAPIS_INGOT);
	public static final ItemSpade REINFORCED_LAPIS_INGOT_MK1_SPADE = new ToolSpade("reinforced_lapis_ingot_mk1_spade", MATERIAL_REINFORCED_LAPIS_INGOT_MK1);
	public static final ItemSpade REINFORCED_LAPIS_INGOT_MK2_SPADE = new ToolSpade("reinforced_lapis_ingot_mk2_spade", MATERIAL_REINFORCED_LAPIS_INGOT_MK2);
	public static final ItemSpade REINFORCED_LAPIS_INGOT_MK3_SPADE = new ToolSpade("reinforced_lapis_ingot_mk3_spade", MATERIAL_REINFORCED_LAPIS_INGOT_MK3);
	public static final ItemSpade REINFORCED_LAPIS_INGOT_MK4_SPADE = new ToolSpade("reinforced_lapis_ingot_mk4_spade", MATERIAL_REINFORCED_LAPIS_INGOT_MK4);
	public static final ItemHoe REINFORCED_WOODEN_PLANKS_MK1_HOE = new ToolHoe("reinforced_wooden_planks_mk1_hoe", MATERIAL_REINFORCED_WOODEN_PLANKS_MK1);
	public static final ItemHoe REINFORCED_WOODEN_PLANKS_MK2_HOE = new ToolHoe("reinforced_wooden_planks_mk2_hoe", MATERIAL_REINFORCED_WOODEN_PLANKS_MK2);
	public static final ItemHoe REINFORCED_WOODEN_PLANKS_MK3_HOE = new ToolHoe("reinforced_wooden_planks_mk3_hoe", MATERIAL_REINFORCED_WOODEN_PLANKS_MK3);
	public static final ItemHoe REINFORCED_WOODEN_PLANKS_MK4_HOE = new ToolHoe("reinforced_wooden_planks_mk4_hoe", MATERIAL_REINFORCED_WOODEN_PLANKS_MK4);
	public static final ItemHoe REINFORCED_COBBLESTONE_MK1_HOE = new ToolHoe("reinforced_cobblestone_mk1_hoe", MATERIAL_REINFORCED_COBBLESTONE_MK1);
	public static final ItemHoe REINFORCED_COBBLESTONE_MK2_HOE = new ToolHoe("reinforced_cobblestone_mk2_hoe", MATERIAL_REINFORCED_COBBLESTONE_MK2);
	public static final ItemHoe REINFORCED_COBBLESTONE_MK3_HOE = new ToolHoe("reinforced_cobblestone_mk3_hoe", MATERIAL_REINFORCED_COBBLESTONE_MK3);
	public static final ItemHoe REINFORCED_COBBLESTONE_MK4_HOE = new ToolHoe("reinforced_cobblestone_mk4_hoe", MATERIAL_REINFORCED_COBBLESTONE_MK4);
	public static final ItemHoe REINFORCED_IRON_INGOT_MK1_HOE = new ToolHoe("reinforced_iron_ingot_mk1_hoe", MATERIAL_REINFORCED_IRON_INGOT_MK1);
	public static final ItemHoe REINFORCED_IRON_INGOT_MK2_HOE = new ToolHoe("reinforced_iron_ingot_mk2_hoe", MATERIAL_REINFORCED_IRON_INGOT_MK2);
	public static final ItemHoe REINFORCED_IRON_INGOT_MK3_HOE = new ToolHoe("reinforced_iron_ingot_mk3_hoe", MATERIAL_REINFORCED_IRON_INGOT_MK3);
	public static final ItemHoe REINFORCED_IRON_INGOT_MK4_HOE = new ToolHoe("reinforced_iron_ingot_mk4_hoe", MATERIAL_REINFORCED_IRON_INGOT_MK4);
	public static final ItemHoe REINFORCED_GOLD_INGOT_MK1_HOE = new ToolHoe("reinforced_gold_ingot_mk1_hoe", MATERIAL_REINFORCED_GOLD_INGOT_MK1);
	public static final ItemHoe REINFORCED_GOLD_INGOT_MK2_HOE = new ToolHoe("reinforced_gold_ingot_mk2_hoe", MATERIAL_REINFORCED_GOLD_INGOT_MK2);
	public static final ItemHoe REINFORCED_GOLD_INGOT_MK3_HOE = new ToolHoe("reinforced_gold_ingot_mk3_hoe", MATERIAL_REINFORCED_GOLD_INGOT_MK3);
	public static final ItemHoe REINFORCED_GOLD_INGOT_MK4_HOE = new ToolHoe("reinforced_gold_ingot_mk4_hoe", MATERIAL_REINFORCED_GOLD_INGOT_MK4);
	public static final ItemHoe REINFORCED_DIAMOND_MK1_HOE = new ToolHoe("reinforced_diamond_mk1_hoe", MATERIAL_REINFORCED_DIAMOND_MK1);
	public static final ItemHoe REINFORCED_DIAMOND_MK2_HOE = new ToolHoe("reinforced_diamond_mk2_hoe", MATERIAL_REINFORCED_DIAMOND_MK2);
	public static final ItemHoe REINFORCED_DIAMOND_MK3_HOE = new ToolHoe("reinforced_diamond_mk3_hoe", MATERIAL_REINFORCED_DIAMOND_MK3);
	public static final ItemHoe REINFORCED_DIAMOND_MK4_HOE = new ToolHoe("reinforced_diamond_mk4_hoe", MATERIAL_REINFORCED_DIAMOND_MK4);
	public static final ItemHoe EMERALD_HOE = new ToolHoe("emerald_hoe", MATERIAL_EMERALD);
	public static final ItemHoe REINFORCED_EMERALD_MK1_HOE = new ToolHoe("reinforced_emerald_mk1_hoe", MATERIAL_REINFORCED_EMERALD_MK1);
	public static final ItemHoe REINFORCED_EMERALD_MK2_HOE = new ToolHoe("reinforced_emerald_mk2_hoe", MATERIAL_REINFORCED_EMERALD_MK2);
	public static final ItemHoe REINFORCED_EMERALD_MK3_HOE = new ToolHoe("reinforced_emerald_mk3_hoe", MATERIAL_REINFORCED_EMERALD_MK3);
	public static final ItemHoe REINFORCED_EMERALD_MK4_HOE = new ToolHoe("reinforced_emerald_mk4_hoe", MATERIAL_REINFORCED_EMERALD_MK4);
	public static final ItemHoe REDSTONE_INGOT_HOE = new ToolHoe("redstone_ingot_hoe", MATERIAL_REDSTONE_INGOT);
	public static final ItemHoe REINFORCED_REDSTONE_INGOT_MK1_HOE = new ToolHoe("reinforced_redstone_ingot_mk1_hoe", MATERIAL_REINFORCED_REDSTONE_INGOT_MK1);
	public static final ItemHoe REINFORCED_REDSTONE_INGOT_MK2_HOE = new ToolHoe("reinforced_redstone_ingot_mk2_hoe", MATERIAL_REINFORCED_REDSTONE_INGOT_MK2);
	public static final ItemHoe REINFORCED_REDSTONE_INGOT_MK3_HOE = new ToolHoe("reinforced_redstone_ingot_mk3_hoe", MATERIAL_REINFORCED_REDSTONE_INGOT_MK3);
	public static final ItemHoe REINFORCED_REDSTONE_INGOT_MK4_HOE = new ToolHoe("reinforced_redstone_ingot_mk4_hoe", MATERIAL_REINFORCED_REDSTONE_INGOT_MK4);
	public static final ItemHoe LAPIS_INGOT_HOE = new ToolHoe("lapis_ingot_hoe", MATERIAL_LAPIS_INGOT);
	public static final ItemHoe REINFORCED_LAPIS_INGOT_MK1_HOE = new ToolHoe("reinforced_lapis_ingot_mk1_hoe", MATERIAL_REINFORCED_LAPIS_INGOT_MK1);
	public static final ItemHoe REINFORCED_LAPIS_INGOT_MK2_HOE = new ToolHoe("reinforced_lapis_ingot_mk2_hoe", MATERIAL_REINFORCED_LAPIS_INGOT_MK2);
	public static final ItemHoe REINFORCED_LAPIS_INGOT_MK3_HOE = new ToolHoe("reinforced_lapis_ingot_mk3_hoe", MATERIAL_REINFORCED_LAPIS_INGOT_MK3);
	public static final ItemHoe REINFORCED_LAPIS_INGOT_MK4_HOE = new ToolHoe("reinforced_lapis_ingot_mk4_hoe", MATERIAL_REINFORCED_LAPIS_INGOT_MK4);
	
	//Armors
	public static final Item REINFORCED_IRON_INGOT_ARMOR_MK1_HELMET = new ArmorBase("reinforced_iron_ingot_armor_mk1_helmet", ARMOR_MATERIAL_REINFORCED_IRON_INGOT_MK1, 1, EntityEquipmentSlot.HEAD);
	public static final Item REINFORCED_IRON_INGOT_ARMOR_MK1_CHESTPLATE = new ArmorBase("reinforced_iron_ingot_armor_mk1_chestplate", ARMOR_MATERIAL_REINFORCED_IRON_INGOT_MK1, 1, EntityEquipmentSlot.CHEST);
	public static final Item REINFORCED_IRON_INGOT_ARMOR_MK1_LEGGINGS = new ArmorBase("reinforced_iron_ingot_armor_mk1_leggings", ARMOR_MATERIAL_REINFORCED_IRON_INGOT_MK1, 2, EntityEquipmentSlot.LEGS);
	public static final Item REINFORCED_IRON_INGOT_ARMOR_MK1_BOOTS = new ArmorBase("reinforced_iron_ingot_armor_mk1_boots", ARMOR_MATERIAL_REINFORCED_IRON_INGOT_MK1, 1, EntityEquipmentSlot.FEET);
	public static final Item REINFORCED_IRON_INGOT_ARMOR_MK2_HELMET = new ArmorBase("reinforced_iron_ingot_armor_mk2_helmet", ARMOR_MATERIAL_REINFORCED_IRON_INGOT_MK2, 1, EntityEquipmentSlot.HEAD);
	public static final Item REINFORCED_IRON_INGOT_ARMOR_MK2_CHESTPLATE = new ArmorBase("reinforced_iron_ingot_armor_mk2_chestplate", ARMOR_MATERIAL_REINFORCED_IRON_INGOT_MK2, 1, EntityEquipmentSlot.CHEST);
	public static final Item REINFORCED_IRON_INGOT_ARMOR_MK2_LEGGINGS = new ArmorBase("reinforced_iron_ingot_armor_mk2_leggings", ARMOR_MATERIAL_REINFORCED_IRON_INGOT_MK2, 2, EntityEquipmentSlot.LEGS);
	public static final Item REINFORCED_IRON_INGOT_ARMOR_MK2_BOOTS = new ArmorBase("reinforced_iron_ingot_armor_mk2_boots", ARMOR_MATERIAL_REINFORCED_IRON_INGOT_MK2, 1, EntityEquipmentSlot.FEET);
	public static final Item REINFORCED_IRON_INGOT_ARMOR_MK3_HELMET = new ArmorBase("reinforced_iron_ingot_armor_mk3_helmet", ARMOR_MATERIAL_REINFORCED_IRON_INGOT_MK3, 1, EntityEquipmentSlot.HEAD);
	public static final Item REINFORCED_IRON_INGOT_ARMOR_MK3_CHESTPLATE = new ArmorBase("reinforced_iron_ingot_armor_mk3_chestplate", ARMOR_MATERIAL_REINFORCED_IRON_INGOT_MK3, 1, EntityEquipmentSlot.CHEST);
	public static final Item REINFORCED_IRON_INGOT_ARMOR_MK3_LEGGINGS = new ArmorBase("reinforced_iron_ingot_armor_mk3_leggings", ARMOR_MATERIAL_REINFORCED_IRON_INGOT_MK3, 2, EntityEquipmentSlot.LEGS);
	public static final Item REINFORCED_IRON_INGOT_ARMOR_MK3_BOOTS = new ArmorBase("reinforced_iron_ingot_armor_mk3_boots", ARMOR_MATERIAL_REINFORCED_IRON_INGOT_MK3, 1, EntityEquipmentSlot.FEET);
	public static final Item REINFORCED_IRON_INGOT_ARMOR_MK4_HELMET = new ArmorBase("reinforced_iron_ingot_armor_mk4_helmet", ARMOR_MATERIAL_REINFORCED_IRON_INGOT_MK4, 1, EntityEquipmentSlot.HEAD);
	public static final Item REINFORCED_IRON_INGOT_ARMOR_MK4_CHESTPLATE = new ArmorBase("reinforced_iron_ingot_armor_mk4_chestplate", ARMOR_MATERIAL_REINFORCED_IRON_INGOT_MK4, 1, EntityEquipmentSlot.CHEST);
	public static final Item REINFORCED_IRON_INGOT_ARMOR_MK4_LEGGINGS = new ArmorBase("reinforced_iron_ingot_armor_mk4_leggings", ARMOR_MATERIAL_REINFORCED_IRON_INGOT_MK4, 2, EntityEquipmentSlot.LEGS);
	public static final Item REINFORCED_IRON_INGOT_ARMOR_MK4_BOOTS = new ArmorBase("reinforced_iron_ingot_armor_mk4_boots", ARMOR_MATERIAL_REINFORCED_IRON_INGOT_MK4, 1, EntityEquipmentSlot.FEET);
	public static final Item REINFORCED_GOLD_INGOT_ARMOR_MK1_HELMET = new ArmorBase("reinforced_gold_ingot_armor_mk1_helmet", ARMOR_MATERIAL_REINFORCED_GOLD_INGOT_MK1, 1, EntityEquipmentSlot.HEAD);
	public static final Item REINFORCED_GOLD_INGOT_ARMOR_MK1_CHESTPLATE = new ArmorBase("reinforced_gold_ingot_armor_mk1_chestplate", ARMOR_MATERIAL_REINFORCED_GOLD_INGOT_MK1, 1, EntityEquipmentSlot.CHEST);
	public static final Item REINFORCED_GOLD_INGOT_ARMOR_MK1_LEGGINGS = new ArmorBase("reinforced_gold_ingot_armor_mk1_leggings", ARMOR_MATERIAL_REINFORCED_GOLD_INGOT_MK1, 2, EntityEquipmentSlot.LEGS);
	public static final Item REINFORCED_GOLD_INGOT_ARMOR_MK1_BOOTS = new ArmorBase("reinforced_gold_ingot_armor_mk1_boots", ARMOR_MATERIAL_REINFORCED_GOLD_INGOT_MK1, 1, EntityEquipmentSlot.FEET);
	public static final Item REINFORCED_GOLD_INGOT_ARMOR_MK2_HELMET = new ArmorBase("reinforced_gold_ingot_armor_mk2_helmet", ARMOR_MATERIAL_REINFORCED_GOLD_INGOT_MK2, 1, EntityEquipmentSlot.HEAD);
	public static final Item REINFORCED_GOLD_INGOT_ARMOR_MK2_CHESTPLATE = new ArmorBase("reinforced_gold_ingot_armor_mk2_chestplate", ARMOR_MATERIAL_REINFORCED_GOLD_INGOT_MK2, 1, EntityEquipmentSlot.CHEST);
	public static final Item REINFORCED_GOLD_INGOT_ARMOR_MK2_LEGGINGS = new ArmorBase("reinforced_gold_ingot_armor_mk2_leggings", ARMOR_MATERIAL_REINFORCED_GOLD_INGOT_MK2, 2, EntityEquipmentSlot.LEGS);
	public static final Item REINFORCED_GOLD_INGOT_ARMOR_MK2_BOOTS = new ArmorBase("reinforced_gold_ingot_armor_mk2_boots", ARMOR_MATERIAL_REINFORCED_GOLD_INGOT_MK2, 1, EntityEquipmentSlot.FEET);
	public static final Item REINFORCED_GOLD_INGOT_ARMOR_MK3_HELMET = new ArmorBase("reinforced_gold_ingot_armor_mk3_helmet", ARMOR_MATERIAL_REINFORCED_GOLD_INGOT_MK3, 1, EntityEquipmentSlot.HEAD);
	public static final Item REINFORCED_GOLD_INGOT_ARMOR_MK3_CHESTPLATE = new ArmorBase("reinforced_gold_ingot_armor_mk3_chestplate", ARMOR_MATERIAL_REINFORCED_GOLD_INGOT_MK3, 1, EntityEquipmentSlot.CHEST);
	public static final Item REINFORCED_GOLD_INGOT_ARMOR_MK3_LEGGINGS = new ArmorBase("reinforced_gold_ingot_armor_mk3_leggings", ARMOR_MATERIAL_REINFORCED_GOLD_INGOT_MK3, 2, EntityEquipmentSlot.LEGS);
	public static final Item REINFORCED_GOLD_INGOT_ARMOR_MK3_BOOTS = new ArmorBase("reinforced_gold_ingot_armor_mk3_boots", ARMOR_MATERIAL_REINFORCED_GOLD_INGOT_MK3, 1, EntityEquipmentSlot.FEET);
	public static final Item REINFORCED_GOLD_INGOT_ARMOR_MK4_HELMET = new ArmorBase("reinforced_gold_ingot_armor_mk4_helmet", ARMOR_MATERIAL_REINFORCED_GOLD_INGOT_MK4, 1, EntityEquipmentSlot.HEAD);
	public static final Item REINFORCED_GOLD_INGOT_ARMOR_MK4_CHESTPLATE = new ArmorBase("reinforced_gold_ingot_armor_mk4_chestplate", ARMOR_MATERIAL_REINFORCED_GOLD_INGOT_MK4, 1, EntityEquipmentSlot.CHEST);
	public static final Item REINFORCED_GOLD_INGOT_ARMOR_MK4_LEGGINGS = new ArmorBase("reinforced_gold_ingot_armor_mk4_leggings", ARMOR_MATERIAL_REINFORCED_GOLD_INGOT_MK4, 2, EntityEquipmentSlot.LEGS);
	public static final Item REINFORCED_GOLD_INGOT_ARMOR_MK4_BOOTS = new ArmorBase("reinforced_gold_ingot_armor_mk4_boots", ARMOR_MATERIAL_REINFORCED_GOLD_INGOT_MK4, 1, EntityEquipmentSlot.FEET);
	public static final Item REINFORCED_DIAMOND_ARMOR_MK1_HELMET = new ArmorBase("reinforced_diamond_armor_mk1_helmet", ARMOR_MATERIAL_REINFORCED_DIAMOND_MK1, 1, EntityEquipmentSlot.HEAD);
	public static final Item REINFORCED_DIAMOND_ARMOR_MK1_CHESTPLATE = new ArmorBase("reinforced_diamond_armor_mk1_chestplate", ARMOR_MATERIAL_REINFORCED_DIAMOND_MK1, 1, EntityEquipmentSlot.CHEST);
	public static final Item REINFORCED_DIAMOND_ARMOR_MK1_LEGGINGS = new ArmorBase("reinforced_diamond_armor_mk1_leggings", ARMOR_MATERIAL_REINFORCED_DIAMOND_MK1, 2, EntityEquipmentSlot.LEGS);
	public static final Item REINFORCED_DIAMOND_ARMOR_MK1_BOOTS = new ArmorBase("reinforced_diamond_armor_mk1_boots", ARMOR_MATERIAL_REINFORCED_DIAMOND_MK1, 1, EntityEquipmentSlot.FEET);
	public static final Item REINFORCED_DIAMOND_ARMOR_MK2_HELMET = new ArmorBase("reinforced_diamond_armor_mk2_helmet", ARMOR_MATERIAL_REINFORCED_DIAMOND_MK2, 1, EntityEquipmentSlot.HEAD);
	public static final Item REINFORCED_DIAMOND_ARMOR_MK2_CHESTPLATE = new ArmorBase("reinforced_diamond_armor_mk2_chestplate", ARMOR_MATERIAL_REINFORCED_DIAMOND_MK2, 1, EntityEquipmentSlot.CHEST);
	public static final Item REINFORCED_DIAMOND_ARMOR_MK2_LEGGINGS = new ArmorBase("reinforced_diamond_armor_mk2_leggings", ARMOR_MATERIAL_REINFORCED_DIAMOND_MK2, 2, EntityEquipmentSlot.LEGS);
	public static final Item REINFORCED_DIAMOND_ARMOR_MK2_BOOTS = new ArmorBase("reinforced_diamond_armor_mk2_boots", ARMOR_MATERIAL_REINFORCED_DIAMOND_MK2, 1, EntityEquipmentSlot.FEET);
	public static final Item REINFORCED_DIAMOND_ARMOR_MK3_HELMET = new ArmorBase("reinforced_diamond_armor_mk3_helmet", ARMOR_MATERIAL_REINFORCED_DIAMOND_MK3, 1, EntityEquipmentSlot.HEAD);
	public static final Item REINFORCED_DIAMOND_ARMOR_MK3_CHESTPLATE = new ArmorBase("reinforced_diamond_armor_mk3_chestplate", ARMOR_MATERIAL_REINFORCED_DIAMOND_MK3, 1, EntityEquipmentSlot.CHEST);
	public static final Item REINFORCED_DIAMOND_ARMOR_MK3_LEGGINGS = new ArmorBase("reinforced_diamond_armor_mk3_leggings", ARMOR_MATERIAL_REINFORCED_DIAMOND_MK3, 2, EntityEquipmentSlot.LEGS);
	public static final Item REINFORCED_DIAMOND_ARMOR_MK3_BOOTS = new ArmorBase("reinforced_diamond_armor_mk3_boots", ARMOR_MATERIAL_REINFORCED_DIAMOND_MK3, 1, EntityEquipmentSlot.FEET);
	public static final Item REINFORCED_DIAMOND_ARMOR_MK4_HELMET = new ArmorBase("reinforced_diamond_armor_mk4_helmet", ARMOR_MATERIAL_REINFORCED_DIAMOND_MK4, 1, EntityEquipmentSlot.HEAD);
	public static final Item REINFORCED_DIAMOND_ARMOR_MK4_CHESTPLATE = new ArmorBase("reinforced_diamond_armor_mk4_chestplate", ARMOR_MATERIAL_REINFORCED_DIAMOND_MK4, 1, EntityEquipmentSlot.CHEST);
	public static final Item REINFORCED_DIAMOND_ARMOR_MK4_LEGGINGS = new ArmorBase("reinforced_diamond_armor_mk4_leggings", ARMOR_MATERIAL_REINFORCED_DIAMOND_MK4, 2, EntityEquipmentSlot.LEGS);
	public static final Item REINFORCED_DIAMOND_ARMOR_MK4_BOOTS = new ArmorBase("reinforced_diamond_armor_mk4_boots", ARMOR_MATERIAL_REINFORCED_DIAMOND_MK4, 1, EntityEquipmentSlot.FEET);
	public static final Item EMERALD_HELMET = new ArmorBase("emerald_helmet", ARMOR_MATERIAL_EMERALD, 1, EntityEquipmentSlot.HEAD);
	public static final Item EMERALD_CHESTPLATE = new ArmorBase("emerald_chestplate", ARMOR_MATERIAL_EMERALD, 1, EntityEquipmentSlot.CHEST);
	public static final Item EMERALD_LEGGINGS = new ArmorBase("emerald_leggings", ARMOR_MATERIAL_EMERALD, 2, EntityEquipmentSlot.LEGS);
	public static final Item EMERALD_BOOTS = new ArmorBase("emerald_boots", ARMOR_MATERIAL_EMERALD, 1, EntityEquipmentSlot.FEET);
	public static final Item REINFORCED_EMERALD_ARMOR_MK1_HELMET = new ArmorBase("reinforced_emerald_armor_mk1_helmet", ARMOR_MATERIAL_REINFORCED_EMERALD_MK1, 1, EntityEquipmentSlot.HEAD);
	public static final Item REINFORCED_EMERALD_ARMOR_MK1_CHESTPLATE = new ArmorBase("reinforced_emerald_armor_mk1_chestplate", ARMOR_MATERIAL_REINFORCED_EMERALD_MK1, 1, EntityEquipmentSlot.CHEST);
	public static final Item REINFORCED_EMERALD_ARMOR_MK1_LEGGINGS = new ArmorBase("reinforced_emerald_armor_mk1_leggings", ARMOR_MATERIAL_REINFORCED_EMERALD_MK1, 2, EntityEquipmentSlot.LEGS);
	public static final Item REINFORCED_EMERALD_ARMOR_MK1_BOOTS = new ArmorBase("reinforced_emerald_armor_mk1_boots", ARMOR_MATERIAL_REINFORCED_EMERALD_MK1, 1, EntityEquipmentSlot.FEET);
	public static final Item REINFORCED_EMERALD_ARMOR_MK2_HELMET = new ArmorBase("reinforced_emerald_armor_mk2_helmet", ARMOR_MATERIAL_REINFORCED_EMERALD_MK2, 1, EntityEquipmentSlot.HEAD);
	public static final Item REINFORCED_EMERALD_ARMOR_MK2_CHESTPLATE = new ArmorBase("reinforced_emerald_armor_mk2_chestplate", ARMOR_MATERIAL_REINFORCED_EMERALD_MK2, 1, EntityEquipmentSlot.CHEST);
	public static final Item REINFORCED_EMERALD_ARMOR_MK2_LEGGINGS = new ArmorBase("reinforced_emerald_armor_mk2_leggings", ARMOR_MATERIAL_REINFORCED_EMERALD_MK2, 2, EntityEquipmentSlot.LEGS);
	public static final Item REINFORCED_EMERALD_ARMOR_MK2_BOOTS = new ArmorBase("reinforced_emerald_armor_mk2_boots", ARMOR_MATERIAL_REINFORCED_EMERALD_MK2, 1, EntityEquipmentSlot.FEET);
	public static final Item REINFORCED_EMERALD_ARMOR_MK3_HELMET = new ArmorBase("reinforced_emerald_armor_mk3_helmet", ARMOR_MATERIAL_REINFORCED_EMERALD_MK3, 1, EntityEquipmentSlot.HEAD);
	public static final Item REINFORCED_EMERALD_ARMOR_MK3_CHESTPLATE = new ArmorBase("reinforced_emerald_armor_mk3_chestplate", ARMOR_MATERIAL_REINFORCED_EMERALD_MK3, 1, EntityEquipmentSlot.CHEST);
	public static final Item REINFORCED_EMERALD_ARMOR_MK3_LEGGINGS = new ArmorBase("reinforced_emerald_armor_mk3_leggings", ARMOR_MATERIAL_REINFORCED_EMERALD_MK3, 2, EntityEquipmentSlot.LEGS);
	public static final Item REINFORCED_EMERALD_ARMOR_MK3_BOOTS = new ArmorBase("reinforced_emerald_armor_mk3_boots", ARMOR_MATERIAL_REINFORCED_EMERALD_MK3, 1, EntityEquipmentSlot.FEET);
	public static final Item REINFORCED_EMERALD_ARMOR_MK4_HELMET = new ArmorBase("reinforced_emerald_armor_mk4_helmet", ARMOR_MATERIAL_REINFORCED_EMERALD_MK4, 1, EntityEquipmentSlot.HEAD);
	public static final Item REINFORCED_EMERALD_ARMOR_MK4_CHESTPLATE = new ArmorBase("reinforced_emerald_armor_mk4_chestplate", ARMOR_MATERIAL_REINFORCED_EMERALD_MK4, 1, EntityEquipmentSlot.CHEST);
	public static final Item REINFORCED_EMERALD_ARMOR_MK4_LEGGINGS = new ArmorBase("reinforced_emerald_armor_mk4_leggings", ARMOR_MATERIAL_REINFORCED_EMERALD_MK4, 2, EntityEquipmentSlot.LEGS);
	public static final Item REINFORCED_EMERALD_ARMOR_MK4_BOOTS = new ArmorBase("reinforced_emerald_armor_mk4_boots", ARMOR_MATERIAL_REINFORCED_EMERALD_MK4, 1, EntityEquipmentSlot.FEET);
	public static final Item REDSTONE_INGOT_HELMET = new ArmorBase("redstone_ingot_helmet", ARMOR_MATERIAL_REDSTONE_INGOT, 1, EntityEquipmentSlot.HEAD);
	public static final Item REDSTONE_INGOT_CHESTPLATE = new ArmorBase("redstone_ingot_chestplate", ARMOR_MATERIAL_REDSTONE_INGOT, 1, EntityEquipmentSlot.CHEST);
	public static final Item REDSTONE_INGOT_LEGGINGS = new ArmorBase("redstone_ingot_leggings", ARMOR_MATERIAL_REDSTONE_INGOT, 2, EntityEquipmentSlot.LEGS);
	public static final Item REDSTONE_INGOT_BOOTS = new ArmorBase("redstone_ingot_boots", ARMOR_MATERIAL_REDSTONE_INGOT, 1, EntityEquipmentSlot.FEET);
	public static final Item REINFORCED_REDSTONE_INGOT_ARMOR_MK1_HELMET = new ArmorBase("reinforced_redstone_ingot_armor_mk1_helmet", ARMOR_MATERIAL_REINFORCED_REDSTONE_INGOT_MK1, 1, EntityEquipmentSlot.HEAD);
	public static final Item REINFORCED_REDSTONE_INGOT_ARMOR_MK1_CHESTPLATE = new ArmorBase("reinforced_redstone_ingot_armor_mk1_chestplate", ARMOR_MATERIAL_REINFORCED_REDSTONE_INGOT_MK1, 1, EntityEquipmentSlot.CHEST);
	public static final Item REINFORCED_REDSTONE_INGOT_ARMOR_MK1_LEGGINGS = new ArmorBase("reinforced_redstone_ingot_armor_mk1_leggings", ARMOR_MATERIAL_REINFORCED_REDSTONE_INGOT_MK1, 2, EntityEquipmentSlot.LEGS);
	public static final Item REINFORCED_REDSTONE_INGOT_ARMOR_MK1_BOOTS = new ArmorBase("reinforced_redstone_ingot_armor_mk1_boots", ARMOR_MATERIAL_REINFORCED_REDSTONE_INGOT_MK1, 1, EntityEquipmentSlot.FEET);
	public static final Item REINFORCED_REDSTONE_INGOT_ARMOR_MK2_HELMET = new ArmorBase("reinforced_redstone_ingot_armor_mk2_helmet", ARMOR_MATERIAL_REINFORCED_REDSTONE_INGOT_MK2, 1, EntityEquipmentSlot.HEAD);
	public static final Item REINFORCED_REDSTONE_INGOT_ARMOR_MK2_CHESTPLATE = new ArmorBase("reinforced_redstone_ingot_armor_mk2_chestplate", ARMOR_MATERIAL_REINFORCED_REDSTONE_INGOT_MK2, 1, EntityEquipmentSlot.CHEST);
	public static final Item REINFORCED_REDSTONE_INGOT_ARMOR_MK2_LEGGINGS = new ArmorBase("reinforced_redstone_ingot_armor_mk2_leggings", ARMOR_MATERIAL_REINFORCED_REDSTONE_INGOT_MK2, 2, EntityEquipmentSlot.LEGS);
	public static final Item REINFORCED_REDSTONE_INGOT_ARMOR_MK2_BOOTS = new ArmorBase("reinforced_redstone_ingot_armor_mk2_boots", ARMOR_MATERIAL_REINFORCED_REDSTONE_INGOT_MK2, 1, EntityEquipmentSlot.FEET);
	public static final Item REINFORCED_REDSTONE_INGOT_ARMOR_MK3_HELMET = new ArmorBase("reinforced_redstone_ingot_armor_mk3_helmet", ARMOR_MATERIAL_REINFORCED_REDSTONE_INGOT_MK3, 1, EntityEquipmentSlot.HEAD);
	public static final Item REINFORCED_REDSTONE_INGOT_ARMOR_MK3_CHESTPLATE = new ArmorBase("reinforced_redstone_ingot_armor_mk3_chestplate", ARMOR_MATERIAL_REINFORCED_REDSTONE_INGOT_MK3, 1, EntityEquipmentSlot.CHEST);
	public static final Item REINFORCED_REDSTONE_INGOT_ARMOR_MK3_LEGGINGS = new ArmorBase("reinforced_redstone_ingot_armor_mk3_leggings", ARMOR_MATERIAL_REINFORCED_REDSTONE_INGOT_MK3, 2, EntityEquipmentSlot.LEGS);
	public static final Item REINFORCED_REDSTONE_INGOT_ARMOR_MK3_BOOTS = new ArmorBase("reinforced_redstone_ingot_armor_mk3_boots", ARMOR_MATERIAL_REINFORCED_REDSTONE_INGOT_MK3, 1, EntityEquipmentSlot.FEET);
	public static final Item REINFORCED_REDSTONE_INGOT_ARMOR_MK4_HELMET = new ArmorBase("reinforced_redstone_ingot_armor_mk4_helmet", ARMOR_MATERIAL_REINFORCED_REDSTONE_INGOT_MK4, 1, EntityEquipmentSlot.HEAD);
	public static final Item REINFORCED_REDSTONE_INGOT_ARMOR_MK4_CHESTPLATE = new ArmorBase("reinforced_redstone_ingot_armor_mk4_chestplate", ARMOR_MATERIAL_REINFORCED_REDSTONE_INGOT_MK4, 1, EntityEquipmentSlot.CHEST);
	public static final Item REINFORCED_REDSTONE_INGOT_ARMOR_MK4_LEGGINGS = new ArmorBase("reinforced_redstone_ingot_armor_mk4_leggings", ARMOR_MATERIAL_REINFORCED_REDSTONE_INGOT_MK4, 2, EntityEquipmentSlot.LEGS);
	public static final Item REINFORCED_REDSTONE_INGOT_ARMOR_MK4_BOOTS = new ArmorBase("reinforced_redstone_ingot_armor_mk4_boots", ARMOR_MATERIAL_REINFORCED_REDSTONE_INGOT_MK4, 1, EntityEquipmentSlot.FEET);
	public static final Item LAPIS_INGOT_HELMET = new ArmorBase("lapis_ingot_helmet", ARMOR_MATERIAL_LAPIS_INGOT, 1, EntityEquipmentSlot.HEAD);
	public static final Item LAPIS_INGOT_CHESTPLATE = new ArmorBase("lapis_ingot_chestplate", ARMOR_MATERIAL_LAPIS_INGOT, 1, EntityEquipmentSlot.CHEST);
	public static final Item LAPIS_INGOT_LEGGINGS = new ArmorBase("lapis_ingot_leggings", ARMOR_MATERIAL_LAPIS_INGOT, 2, EntityEquipmentSlot.LEGS);
	public static final Item LAPIS_INGOT_BOOTS = new ArmorBase("lapis_ingot_boots", ARMOR_MATERIAL_LAPIS_INGOT, 1, EntityEquipmentSlot.FEET);
	public static final Item REINFORCED_LAPIS_INGOT_ARMOR_MK1_HELMET = new ArmorBase("reinforced_lapis_ingot_armor_mk1_helmet", ARMOR_MATERIAL_REINFORCED_LAPIS_INGOT_MK1, 1, EntityEquipmentSlot.HEAD);
	public static final Item REINFORCED_LAPIS_INGOT_ARMOR_MK1_CHESTPLATE = new ArmorBase("reinforced_lapis_ingot_armor_mk1_chestplate", ARMOR_MATERIAL_REINFORCED_LAPIS_INGOT_MK1, 1, EntityEquipmentSlot.CHEST);
	public static final Item REINFORCED_LAPIS_INGOT_ARMOR_MK1_LEGGINGS = new ArmorBase("reinforced_lapis_ingot_armor_mk1_leggings", ARMOR_MATERIAL_REINFORCED_LAPIS_INGOT_MK1, 2, EntityEquipmentSlot.LEGS);
	public static final Item REINFORCED_LAPIS_INGOT_ARMOR_MK1_BOOTS = new ArmorBase("reinforced_lapis_ingot_armor_mk1_boots", ARMOR_MATERIAL_REINFORCED_LAPIS_INGOT_MK1, 1, EntityEquipmentSlot.FEET);
	public static final Item REINFORCED_LAPIS_INGOT_ARMOR_MK2_HELMET = new ArmorBase("reinforced_lapis_ingot_armor_mk2_helmet", ARMOR_MATERIAL_REINFORCED_LAPIS_INGOT_MK2, 1, EntityEquipmentSlot.HEAD);
	public static final Item REINFORCED_LAPIS_INGOT_ARMOR_MK2_CHESTPLATE = new ArmorBase("reinforced_lapis_ingot_armor_mk2_chestplate", ARMOR_MATERIAL_REINFORCED_LAPIS_INGOT_MK2, 1, EntityEquipmentSlot.CHEST);
	public static final Item REINFORCED_LAPIS_INGOT_ARMOR_MK2_LEGGINGS = new ArmorBase("reinforced_lapis_ingot_armor_mk2_leggings", ARMOR_MATERIAL_REINFORCED_LAPIS_INGOT_MK2, 2, EntityEquipmentSlot.LEGS);
	public static final Item REINFORCED_LAPIS_INGOT_ARMOR_MK2_BOOTS = new ArmorBase("reinforced_lapis_ingot_armor_mk2_boots", ARMOR_MATERIAL_REINFORCED_LAPIS_INGOT_MK2, 1, EntityEquipmentSlot.FEET);
	public static final Item REINFORCED_LAPIS_INGOT_ARMOR_MK3_HELMET = new ArmorBase("reinforced_lapis_ingot_armor_mk3_helmet", ARMOR_MATERIAL_REINFORCED_LAPIS_INGOT_MK3, 1, EntityEquipmentSlot.HEAD);
	public static final Item REINFORCED_LAPIS_INGOT_ARMOR_MK3_CHESTPLATE = new ArmorBase("reinforced_lapis_ingot_armor_mk3_chestplate", ARMOR_MATERIAL_REINFORCED_LAPIS_INGOT_MK3, 1, EntityEquipmentSlot.CHEST);
	public static final Item REINFORCED_LAPIS_INGOT_ARMOR_MK3_LEGGINGS = new ArmorBase("reinforced_lapis_ingot_armor_mk3_leggings", ARMOR_MATERIAL_REINFORCED_LAPIS_INGOT_MK3, 2, EntityEquipmentSlot.LEGS);
	public static final Item REINFORCED_LAPIS_INGOT_ARMOR_MK3_BOOTS = new ArmorBase("reinforced_lapis_ingot_armor_mk3_boots", ARMOR_MATERIAL_REINFORCED_LAPIS_INGOT_MK3, 1, EntityEquipmentSlot.FEET);
	public static final Item REINFORCED_LAPIS_INGOT_ARMOR_MK4_HELMET = new ArmorBase("reinforced_lapis_ingot_armor_mk4_helmet", ARMOR_MATERIAL_REINFORCED_LAPIS_INGOT_MK4, 1, EntityEquipmentSlot.HEAD);
	public static final Item REINFORCED_LAPIS_INGOT_ARMOR_MK4_CHESTPLATE = new ArmorBase("reinforced_lapis_ingot_armor_mk4_chestplate", ARMOR_MATERIAL_REINFORCED_LAPIS_INGOT_MK4, 1, EntityEquipmentSlot.CHEST);
	public static final Item REINFORCED_LAPIS_INGOT_ARMOR_MK4_LEGGINGS = new ArmorBase("reinforced_lapis_ingot_armor_mk4_leggings", ARMOR_MATERIAL_REINFORCED_LAPIS_INGOT_MK4, 2, EntityEquipmentSlot.LEGS);
	public static final Item REINFORCED_LAPIS_INGOT_ARMOR_MK4_BOOTS = new ArmorBase("reinforced_lapis_ingot_armor_mk4_boots", ARMOR_MATERIAL_REINFORCED_LAPIS_INGOT_MK4, 1, EntityEquipmentSlot.FEET);
	
	
	
}
